config/routes.rb
Rails.application.routes.draw do

# 顧客用Devise
devise_for :users,skip: [:passwords],controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用Devise
devise_for :admin, skip: [:passwords] ,controllers: {
  registrations: "admin/registrations",
  sessions: "admin/sessions"
}

#ログアウト時にルートエラーになるため追記
devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
devise_scope :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end

#ゲストログイン機能用ルーティング
post '/homes/guest_sign_in', to: 'public/homes#guest_sign_in'

#ユーザー側TOPページ
root :to => "public/homes#top"
get "about" => "public/homes#about", as: "about"

#ユーザー側ルーティング
scope module: 'public' do
  resources :members, only: [:index,:show,:edit,:update]
  resources :meals, only: [:new,:create,:destroy]
  resources :foods, only: [:index,:new,:create,:edit,:update,:destroy]
  resources :comments, only: [:create,:destroy]
  resources :dates, only: [:show]
  resources :nices, only: [:index,:create,:destroy]
  resources :records, only: [:index]
  get "search" => "searches#index"
end

#管理者側ルーティング
namespace :admin do
  root :to => "homes#top"
  resources :members, only: [:index,:show,:update]
  resources :foods, only: [:index,:show,:update,:destroy]
  resources :comments, only: [:index,:destroy]
  resources :nices, only: [:index,:destroy]

end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  def self.search_by_tag(tag)
    where("comment LIKE ?", "%##{tag}%")
  end

    #enum関連
    enum timeframe: { morning: 0, lunch: 1, dinner: 2, snack: 3 }


    validates :comment, presence: true, length: { minimum: 1, maximum: 200 }
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
before_action :authenticate_admin!

  def index
    @comments = Comment.all
  end

  def destroy
    comment = Comment.find(params[:id])
    flash[:notice] = "ID: #{comment.id} - [#{comment.comment}]を削除しました。"
    comment.destroy
    redirect_to request.referer
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
  <h2 class="mt-3">コメント一覧</h2>
  <% if notice.present? %>
    <div class="mt-4 text-primary">
      <h5><%= notice %></h5>
    </div>
  <% end %>
<% if @comments.empty? %>
<h3 class="mt-5">まだコメントされた投稿がありません。</h3>
<% else %>
  <div class="row">
    <div class="col-md-12 mx-auto mt-3">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>コメントユーザー</th>
            <th>投稿先</th>
            <th>内容</th>
            <th>時間</th>
            <th></th>
          </tr>
        </thead>
      <tbody>
<% @comments.each do |comment| %>
        <tr>
          <td><%= comment.id%></td>
          <td><%= User.find(comment.comment_user_id).name %></td>
          <td><%= User.find(comment.user_id).name %>(<%= comment.ymd %>：<%= comment.timeframe_i18n %>)</td>
          <td><%= comment.comment %></td>
          <td><%= comment.created_at.strftime('%Y-%-m-%-d %H:%M:%S') %></td>
          <td><%= link_to "削除", admin_comment_path(comment.id), data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？"},class: "btn btn-danger" %></td>
        </tr>
<% end %>
      </tbody>
    </thead>
  </table>
<% end %>