config/routes.rb
Rails.application.routes.draw do

# 顧客用Devise
devise_for :users,skip: [:passwords],controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用Devise
devise_for :admin, skip: [:passwords] ,controllers: {
  registrations: "admin/registrations",
  sessions: "admin/sessions"
}

#ログアウト時にルートエラーになるため追記
devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
devise_scope :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end

#ゲストログイン機能用ルーティング
post '/homes/guest_sign_in', to: 'public/homes#guest_sign_in'

#ユーザー側TOPページ
root :to => "public/homes#top"
get "about" => "public/homes#about", as: "about"

#ユーザー側ルーティング
scope module: 'public' do
  resources :members, only: [:index,:show,:edit,:update]
  resources :meals, only: [:new,:create,:destroy]
  resources :foods, only: [:index,:new,:create,:edit,:update,:destroy]
  resources :comments, only: [:create,:destroy]
  resources :dates, only: [:show]
  resources :nices, only: [:index,:create,:destroy]
  resources :records, only: [:index]
  get "search" => "searches#index"
end

#管理者側ルーティング
namespace :admin do
  root :to => "homes#top"
  resources :members, only: [:index,:show,:update]
  resources :foods, only: [:index,:show,:update,:destroy]
  resources :comments, only: [:index,:destroy]
  resources :nices, only: [:index,:destroy]

end

end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :meals, dependent: :destroy

validates :name, presence: true, length: { minimum: 1, maximum: 50 }
validates :calorie, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to:9999 }
validates :protein, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to:9999, allow_float: true }
validates :fat, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to:9999, allow_float: true }
validates :carbohydrate, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to:9999, allow_float: true }
validates :explanation, presence: true, length: { minimum: 1, maximum: 150 }


end

app/controllers/admin/foods_controller.rb
class Admin::FoodsController < ApplicationController

before_action :authenticate_admin!

  def index
    @foods = Food.all
  end

  def show

    @food = Food.find(params[:id])

  end

  def update
    @food = Food.find(params[:id])
   if @food.update(food_params)
    redirect_to admin_foods_path
   else
    render "show",status: :unprocessable_entity
   end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to admin_foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :calorie, :protein, :fat, :carbohydrate, :explanation)
  end
end

app/helpers/admin/foods_helper.rb
module Admin::FoodsHelper
end

app/views/admin/foods/index.html.erb
  <h2 class="mt-3">食品一覧</h2>
  <% if @foods.empty? %>
<h3 class="mt-5">まだ食品の登録がありません。</h3>
<% else %>
  <div class="row">
    <div class="col-md-12 mx-auto mt-3">
      <table class="table table-striped">
        <thead>

          <tr>
            <th></th>
          </tr>
        <tbody>
        </tbody>

          <tr>
      <th>ID</th>
      <th>食品名</th>
      <th>投稿ユーザー</th>
      <th>カロリー(kcal)</th>
      <th>タンパク質(g)</th>
      <th>脂質(g)</th>
      <th>炭水化物(g)</th>
      <th>説明</th>
      <th></th>
          </tr>
      </thead>
        <tbody>
              <% @foods.each do |food| %>
      <tr>
        <td><%= food.id %></td>
        <td><%= link_to food.name,admin_food_path(food.id) %></td>
        <td><%= User.find(food.user_id).name %></td>
        <td><%= food.calorie %></td>
        <td><%= food.protein %></td>
        <td><%= food.fat %></td>
        <td><%= food.carbohydrate %></td>
        <td><%= food.explanation %></td>


       <td><%= link_to "削除", admin_food_path(food.id), data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？\r\n削除すると今まで登録していた「#{h(food.name)}」に関する食事内容がすべて削除されます。"},class: "btn btn-danger" %></td>
      </tr>
      <% end %>
            <% end %>
  </tbody>
</table>
<table>
  </div>
  </div>

app/views/admin/foods/show.html.erb
<div class="row justify-content-center">
   <div class="col-8 m-0 mb-5">
<h3 class="mb-5">食品編集</h3>
<%= form_with model:@food,url: admin_food_path(@food.id),local: true do |f| %>
     <div class="mb-3">
    <%= f.label :name,"食品名" %><br />
    <%= f.text_field :name,class:"form-control",placeholder:"例：バナナ"%>
  </div>
      <div class="mb-3">
    <%= f.label :calorie,"カロリー" %><br />
    <%= f.number_field :calorie,min:0,max:9999,class:"form-control",placeholder:"kcal単位"%>
  </div>
    <div class="mb-3">
    <%= f.label :protein,"タンパク質" %><br />
    <%= f.number_field :protein,min:0,max:9999,step: 0.1,class:"form-control",placeholder:"グラム単位"%>
  </div>
      <div class="mb-3">
    <%= f.label :fat,"脂質" %><br />
    <%= f.number_field :fat,min:0,max:9999,step: 0.1,class:"form-control",placeholder:"グラム単位"%>
  </div>
      <div class="mb-3">
    <%= f.label :carbohydrate,"炭水化物" %><br />
    <%= f.number_field :carbohydrate,min:0,max:9999,step: 0.1,class:"form-control",placeholder:"グラム単位"%>
  </div>
    <div class="mb-3">
    <%= f.label :explanation,"説明" %><br />
    <%= f.text_area :explanation,class:"form-control",placeholder:"食品の説明を入力してください。"%>
  </div>
   <%=f.submit '編集',class: "btn btn-sm btn btn-success",data: { "turbo-confirm": "編集を実行しますか？" }%>
<% end %>
 <div class="field pt-3 pb-2 text-danger">
  <% if @food.errors.any? %>
    <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
    </div>
  </div>
    </div>