config/routes.rb
Rails.application.routes.draw do

# 顧客用Devise
devise_for :users,skip: [:passwords],controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用Devise
devise_for :admin, skip: [:passwords] ,controllers: {
  registrations: "admin/registrations",
  sessions: "admin/sessions"
}

#ログアウト時にルートエラーになるため追記
devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
devise_scope :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end

#ゲストログイン機能用ルーティング
post '/homes/guest_sign_in', to: 'public/homes#guest_sign_in'

#ユーザー側TOPページ
root :to => "public/homes#top"
get "about" => "public/homes#about", as: "about"

#ユーザー側ルーティング
scope module: 'public' do
  resources :members, only: [:index,:show,:edit,:update]
  resources :meals, only: [:new,:create,:destroy]
  resources :foods, only: [:index,:new,:create,:edit,:update,:destroy]
  resources :comments, only: [:create,:destroy]
  resources :dates, only: [:show]
  resources :nices, only: [:index,:create,:destroy]
  resources :records, only: [:index]
  get "search" => "searches#index"
end

#管理者側ルーティング
namespace :admin do
  root :to => "homes#top"
  resources :members, only: [:index,:show,:update]
  resources :foods, only: [:index,:show,:update,:destroy]
  resources :comments, only: [:index,:destroy]
  resources :nices, only: [:index,:destroy]

end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  def self.search_by_tag(tag)
    where("comment LIKE ?", "%##{tag}%")
  end

    #enum関連
    enum timeframe: { morning: 0, lunch: 1, dinner: 2, snack: 3 }


    validates :comment, presence: true, length: { minimum: 1, maximum: 200 }
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :meals, dependent: :destroy

validates :name, presence: true, length: { minimum: 1, maximum: 50 }
validates :calorie, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to:9999 }
validates :protein, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to:9999, allow_float: true }
validates :fat, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to:9999, allow_float: true }
validates :carbohydrate, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to:9999, allow_float: true }
validates :explanation, presence: true, length: { minimum: 1, maximum: 150 }


end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  belongs_to :food

  validates :food_id, presence: true
  validates :ymd, presence: true
  validates :timeframe,presence:  true
  validates :quantity, presence: true
end

app/models/nice.rb
class Nice < ApplicationRecord
  belongs_to :user

    #enum関連
    enum timeframe: { morning: 0, lunch: 1, dinner: 2, snack: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :foods, dependent: :destroy
  has_many :meals, dependent: :destroy
  has_many :nices, dependent: :destroy
  has_many :comments, dependent: :destroy

  #enum関連
  enum purpose: { training: 0, diet: 1, health: 2, etc: 3 }
  enum sex: { men: 0, women: 1 }
  enum activity: { sedentary: 0, light: 1, moderate: 2, intense: 3, very_intense: 4 }


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  #年齢計算メゾット
  def age
    now = Time.zone.now
    age = now.year - birthday.year

    # 誕生日を過ぎていない場合は、1歳減らす
    age -= 1 if now.month < birthday.month || (now.month == birthday.month && now.day < birthday.day)

    age
  end

#新規登録の追加バリデーション
  validates :name,  presence: true,  length: { minimum: 1, maximum: 20 }
  validates :height, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 300, allow_float: true }
  validates :weight, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 300, allow_float: true }
  validates :purpose, presence: true, length: { minimum: 1, maximum: 100 }
  validates :profile, length: { minimum: 0, maximum: 150 }
  validates :sex, presence: true
  validates :activity, presence: true
  validates :birthday, presence: true
  validates :status, inclusion: { in: [true, false] }

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
before_action :authenticate_admin!

  def index
    @comments = Comment.all
  end

  def destroy
    comment = Comment.find(params[:id])
    flash[:notice] = "ID: #{comment.id} - [#{comment.comment}]を削除しました。"
    comment.destroy
    redirect_to request.referer
  end

end

app/controllers/admin/foods_controller.rb
class Admin::FoodsController < ApplicationController

before_action :authenticate_admin!

  def index
    @foods = Food.all
  end

  def show

    @food = Food.find(params[:id])

  end

  def update
    @food = Food.find(params[:id])
   if @food.update(food_params)
    redirect_to admin_foods_path
   else
    render "show",status: :unprocessable_entity
   end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to admin_foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :calorie, :protein, :fat, :carbohydrate, :explanation)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @members = User.where.not(email: 'guest@example.com')
    @guest = User.find_by(email: 'guest@example.com')
  end

  def show
    @member = User.find(params[:id])
  end

  def update
    @member = User.find(params[:id])
   if @member.update(member_params)
       redirect_to admin_members_path
     else
       render "show", status: :unprocessable_entity
     end
  end

  private


def member_params
  params.require(:user).permit(:name, :height, :weight, :purpose, :profile, :status,:sex,:activity,:birthday)
end


end

app/controllers/admin/nices_controller.rb
class Admin::NicesController < ApplicationController
before_action :authenticate_admin!

  def index
    @nices = Nice.all
  end

  def destroy
    @nice = Nice.find(params[:id])
    @nice.destroy
    redirect_to admin_nice_path
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # ログイン後のリダイレクト先
def after_sign_in_path_for(resource_or_scope)
  case resource_or_scope

  when Admin
    admin_root_path

  when User
    #会員ステータスが有効かチェック
    unless current_user.status == true
      member_path(current_user.id, year: Time.zone.now.year, month: Time.zone.now.month, day: Time.zone.now.day)
    else
      sign_out(current_user)
      flash[:alert] =  "退会済みであるためログインできません。"
      root_path

    end
  end
end

  # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :height, :weight, :purpose, :profile,:sex,:activity,:birthday])
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/foods_helper.rb
module Admin::FoodsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/nices_helper.rb
module Admin::NicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>

  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-dark pt-5 pb-4 fixed-bottom">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
          </div>
        </div>
      </div>
    </footer>

app/views/layouts/_header.html.erb
<header style="border-bottom: 5px solid #d8d8d8">
  <div class="container col-sm-12 col-md-10 col-lg-12 col-xl-12 d-flex justify-content-between pr-0">

    <!--ロゴ-->
    <div class="row">
      <% if user_signed_in? %>
      <a class="navbar-brand text-dark" href="/">
      <% elsif admin_signed_in? %>
      <a class="navbar-brand text-dark" href="/admin">
      <% else %>
      <a class="navbar-brand text-dark" href="/">
      <% end %>
        <h1>FoodLog</h1>
      </a>
    </div>

    <!--リンク一覧-->
    <div class="row-auto justify-content-end d-flex align-content-center flex-wrap">
      <nav class="navbar navbar-expand-lg navbar-expand-md navbar-dark pt-3">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li class="m-3 d-flex align-items-center">
              ようこそ、管理者さん！
            </li>
            <li class="m-3">
              <%= link_to "Users", admin_members_path, class: 'nav-link text-center text-dark border border-secondary rounded', style: "width: 80px" %>
            </li>
            <li class="m-3">
              <%= link_to "Comments", admin_comments_path, class: 'nav-link text-dark border border-secondary rounded' %>
            </li>
            <li class="m-3">
              <%= link_to "Foods", admin_foods_path, class: 'nav-link text-dark border border-secondary rounded' %>
            </li>
            <li class="m-3">
              <%= link_to "Nices", admin_nices_path, class: 'nav-link text-dark border border-secondary rounded' %>
            </li>
            <li class="m-3">
              <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark border border-secondary rounded' %>
            </li>

          <% elsif user_signed_in? %>

            <li class="m-3 d-flex align-items-center">
              ようこそ、<%= current_user.name %>さん！
            </li>
            <li class="m-3">
              <%= link_to "About", about_path, class: 'nav-link text-center text-dark border border-secondary rounded', style: "width: 80px" %>
            </li>
            <li class="m-3">
              <%= link_to "MyPage", member_path(current_user.id, year: Time.zone.now.year, month: Time.zone.now.month, day: Time.zone.now.day), class: 'nav-link text-dark border border-secondary rounded' %>
            </li>
            <li class="m-3">
              <%= link_to "Users", members_path, class: 'nav-link text-dark border border-secondary rounded' %>
            </li>
            <li class="m-3">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark border border-secondary rounded' %>
            </li>
          <% else %>

            <li class="m-3">
              <%= link_to "About", about_path, class: 'nav-link text-center text-dark border border-secondary rounded', style: "width: 80px" %>
            </li>
            <li class="m-3">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark border border-secondary rounded' %>
            </li>
            <li class="m-3">
              <%= link_to "ログイン", root_path, class: 'nav-link text-dark border border-secondary rounded' %>
            </li>

          <% end %>
          </ul>
        </div>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <!--ヘッダー-->
    <%= render 'layouts/header' %>

    <main style="padding-bottom:100px">

      <div class='container my-5 px-sm-2'>
    <% if user_signed_in? %>
        <%= render 'public/searches/search_form' %>
    <% end %>
      <%= yield %>
    </main>

    <!--フッター-->
    <%= render 'layouts/footer' %>
  </body>
</html>